### ISSUE TITLE
Error by applying the template to sub site - Issue is the default task list by source subsite

### ISSUE THREAD

**Issue by erwinvanhunen** [SharePoint/PnP-Sites-Core#1460]
_From @Vintaurus on October 30, 2017 14:27_

Version: SharePoint 2016 German without Feature Pack 2

### Expected behavior 
Get template from source subsite and apply it to new subsite. (Both in German)

### Actual behavior 
This error exists only, if the default task list is added to the source site (in German). Without task list I can get the template from source site and apply it to new subsite. 

With the default task list I got this error message: 
Apply-PnPProvisioningTemplate : Die Spalte 'Description' ist nicht vorhanden. Möglicherweise wurde sie von einem anderen Benutzer gelöscht.
At C:\Users\Administrator\OneDrive - Vincent Rothländer\Development\10001\CSOM-Scripts\DMSES_ProvisioningSubsite.ps1:69 char:5
+     Apply-PnPProvisioningTemplate -Path $projectWebTemplate -Web $global:project ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : WriteError: (:) [Apply-PnPProvisioningTemplate], ServerException
    + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Provisioning.ApplyProvisioningTemplate
                
### Steps to reproduce behavior
1. Create subsite in German and the template is default team site
2. Add default lists: Contacts "Kontakte", Tasks "Aufgaben", Calender "Kalender", Wiki Library "Projektinformationen"
3.  Get-PnPProvisioningTemplate -Out $projectWebTemplate -IncludeSiteCollectionTermGroup -IncludeNativePublishingFiles -IncludeSearchConfiguration -PersistBrandingFiles -PersistPublishingFiles -FORCE -Verbose -Debug
4. Create new subsite in the same site collection.
New-PnPWeb -Title "$projectTitle" -Url $global:projectUrl -Template "STS#0" -BreakInheritance -Locale 1031
5. Apply-PnPProvisioningTemplate -Path $projectWebTemplate -Web $global:projectUrl -ClearNavigation -ProvisionContentTypesToSubWebs
--> I tried some different parameters and without parameters. The effect is the same. 

### Which version of the PnP-PowerShell Cmdlets are you using?
- [ ] PnP PowerShell for SharePoint 2013
- [X] PnP PowerShell for SharePoint 2016
- [ ] PnP PowerShell for SharePoint Online

### What is the version of the Cmdlet module you are running?
2.19.1710.2

### How did you install the PnP-PowerShell Cmdlets? 
- [X] MSI Installed downloaded from GitHub
- [ ] Installed through the PowerShell Gallery with Install-Module
- [ ] Other means

_Copied from original issue: SharePoint/PnP-PowerShell#1181_
